// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1vhEOJfD-7lM24cq7qEfX_8_ArvQ3QM',
    appId: '1:678186919993:web:b183a0627d38b3f4cdc5e8',
    messagingSenderId: '678186919993',
    projectId: 'fpoupex-app',
    authDomain: 'fpoupex-app.firebaseapp.com',
    storageBucket: 'fpoupex-app.firebasestorage.app',
  );

  // Configurações de teste - substitua pelas suas configurações reais

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_zbZTPCghB0KaKykwZ0qWiFBjADR0Mg',
    appId: '1:678186919993:android:1d8660122d6196f4cdc5e8',
    messagingSenderId: '678186919993',
    projectId: 'fpoupex-app',
    storageBucket: 'fpoupex-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    storageBucket: 'demo-poupex-test.appspot.com',
    iosBundleId: 'com.example.projetoPity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    storageBucket: 'demo-poupex-test.appspot.com',
    iosBundleId: 'com.example.projetoPity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf1vhEOJfD-7lM24cq7qEfX_8_ArvQ3QM',
    appId: '1:678186919993:web:0cee4a3d6c0f75e4cdc5e8',
    messagingSenderId: '678186919993',
    projectId: 'fpoupex-app',
    authDomain: 'fpoupex-app.firebaseapp.com',
    storageBucket: 'fpoupex-app.firebasestorage.app',
  );

}