// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configurações de teste - substitua pelas suas configurações reais
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    authDomain: 'demo-poupex-test.firebaseapp.com',
    storageBucket: 'demo-poupex-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    storageBucket: 'demo-poupex-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    storageBucket: 'demo-poupex-test.appspot.com',
    iosBundleId: 'com.example.projetoPity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    storageBucket: 'demo-poupex-test.appspot.com',
    iosBundleId: 'com.example.projetoPity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-poupex-test',
    authDomain: 'demo-poupex-test.firebaseapp.com',
    storageBucket: 'demo-poupex-test.appspot.com',
  );
}